### ISSUE TITLE
Getting ArgumentError...undefined to_sym after upgrading to 5.0.0

### ISSUE THREAD

**Issue by jasnow** [thoughtbot/factory_bot#1259]
1. Clone my fork of repo: https://github.com/jasnow/24pullrequests
 2. Run "bundle install" then "rake" to see that everything is green.
 3. Remove ", '4.11.1' # 2/7/2019: LOCKED DOWN" from my "gem 'factory_bot_rails'" line in Gemfile file.
4. Run "bundle update" and "rake" and you now get 1 failed test:
```
     Failure/Error: expect { create :project, parameters }.to raise_error ArgumentError

       expected ArgumentError, got #<NoMethodError: undefined method `to_sym' for <ActionController::Parameters {"admin"=>1} permitted: false>:ActionController::Parameters
       Did you mean?  to_s> with backtrace:
         # /Users/macbookpro/.rvm/gems/ruby-2.6.1@ruby2.6-rails5.2/gems/factory_bot-5.0.0/lib/factory_bot/factory_runner.rb:8:in `map'
         # /Users/macbookpro/.rvm/gems/ruby-2.6.1@ruby2.6-rails5.2/gems/factory_bot-5.0.0/lib/factory_bot/factory_runner.rb:8:in `initialize'
         # /Users/macbookpro/.rvm/gems/ruby-2.6.1@ruby2.6-rails5.2/gems/factory_bot-5.0.0/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `new'
         # /Users/macbookpro/.rvm/gems/ruby-2.6.1@ruby2.6-rails5.2/gems/factory_bot-5.0.0/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
         # ./spec/controllers/projects_controller_spec.rb:94:in `block (4 levels) in <top (required)>'
         # ./spec/controllers/projects_controller_spec.rb:94:in `block (3 levels) in <top (required)>'
     # ./spec/controllers/projects_controller_spec.rb:94:in `block (3 levels) in <top (required)>'
```
Hope this helps... Feel free to add comments and questions if you need more information.
Thanks

**Comment by composerinteralia** [comment]
Yeah, that is not a particularly helpful error, is it?

Is has to do with your passing in an `ActionController::Parameters` object instead of a hash. It is being interpreted as a trait instead of a list of attributes to override, and traits need to be symbols or strings. As a quick fix you could do something like what was done in https://github.com/jasnow/24pullrequests/commit/182665e4a96d385f39e386cb57ccac565ffd38da.

I can look into why this behavior was changed, and at the very least we should be able to provide a more helpful error message. The code causing the error is here: https://github.com/thoughtbot/factory_bot/blob/0a072064c536818bec517cd00b56ac36b09c0f4a/lib/factory_bot/factory_runner.rb#L7-L8

**Comment by jasnow** [comment]
@composerinteralia - FYI: I tried your above "quick fix" suggestion and still get an error.

**Comment by composerinteralia** [comment]
Oops, sorry about that. Looking at that spec again, it was only passing with factory_bot 4.11 because `create :project, parameters` was raising:
``` 
ArgumentError:
  Trait not registered: {"admin"=>1}`
```
That error is coming from factory_bot, telling us that the factory does not have a trait called `{"admin"=>1}`. So that `parameters` argument was being treated as a trait all along. Given that fact, I'm not sure that spec is testing what it says it is.

Those two `ActionController::Parameter` specs look like the might be trying to test Rails itself, so you might consider whether you need them at all.

---

We should still fix that error message though.  We switched from an `ArgumentError` to a `KeyError` in factory_bot 5.0.0, so I would like to replace the confusing :
```
NoMethodError:
  undefined method `to_sym' for <ActionController::Parameters {"admin"=>1} permitted: false>
```
And instead I would want to see something like:
```
KeyError:
  Trait not registered: <ActionController::Parameters {"admin"=>1} permitted: false>
```

Technical details:

We might need to remove the `.map(&:to_sym)` we added in https://github.com/thoughtbot/factory_bot/commit/f4ad4f0c87747b5511288004bb1ba249478e73c9 and handle the indifferent trait access in some other way, maybe inside of the `FactoryBot::Definition`.

**Comment by jasnow** [comment]
@composerinteralia - Thanks for your analysis.

**Comment by composerinteralia** [comment]
I just released 5.0.2 which has a fix for this

**Comment by jasnow** [comment]
@composerinteralia - Thanks

**Comment by jasnow** [comment]
Verified fix (after changing the repo's spec). Thanks.

**Comment by composerinteralia** [comment]
Thanks for the issue!
